import { expect, test } from '@playwright/test'
import { installSafeRoutes } from './support/routes'

test('re-login, plan, timer, manual revision, reflection AI, review, and admin summary complete safely', async ({ page }) => {
  const fixture = await installSafeRoutes(page)
  await page.goto('/')
  await page.locator('#lem').fill('release-admin@example.test')
  await page.locator('#lpw').fill('fixture-password')
  await page.getByRole('button', { name: 'Sign In' }).click()
  await expect(page.locator('.ph-title')).toHaveText('Dashboard')
  await page.locator('button[onclick="doLogout()"]').click()
  await expect(page.locator('#login-screen')).toBeVisible()
  await page.locator('#lem').fill('release-admin@example.test')
  await page.locator('#lpw').fill('fixture-password')
  await page.getByRole('button', { name: 'Sign In' }).click()

  await page.goto('/time-management/')
  await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible()
  await page.getByLabel('Planned minutes').fill('420')
  await page.getByRole('button', { name: 'Save plan' }).click()
  await expect(page.getByText('Plan saved with a 60 minute difference.', { exact: true })).toBeVisible()
  await page.getByLabel('Optional CRM link').fill('Fixture')
  await page.getByRole('option', { name: 'CONTACT: Safe Fixture Contact' }).click()
  await page.getByRole('button', { name: 'Start timer' }).click()
  await expect(page.getByText(/Running: Core work/)).toBeVisible()
  await page.getByLabel('Timer category').selectOption('20000000-0000-4000-8000-000000000002')
  await page.getByRole('button', { name: 'Switch timer' }).click()
  await expect(page.getByText(/Running: Client service/)).toBeVisible()

  await page.locator('nav[aria-label="Time management"]').getByRole('link', { name: 'Records' }).click()
  await page.getByRole('button', { name: 'Add manual entry' }).click()
  await page.getByRole('button', { name: 'Save manual entry' }).click()
  await page.getByRole('button', { name: 'Confirm manual entry' }).click()
  await expect(page.getByText('Manual entry saved.')).toBeVisible()
  await page.getByRole('article').filter({ hasText: 'Initial note' }).getByRole('button', { name: 'Edit record' }).click()
  await page.getByLabel('Notes').fill('Safe revised note')
  await page.getByRole('button', { name: 'Save revision' }).click()
  await page.getByRole('button', { name: 'Confirm revision' }).click()
  await expect(page.getByText('Safe revised note')).toBeVisible()

  await page.locator('nav[aria-label="Time management"]').getByRole('link', { name: 'Review' }).click()
  await expect(page.getByText('Plan and time complete; reflection pending')).toBeVisible()
  await page.getByRole('textbox', { name: 'Daily reflection' }).fill('Private reflection kept inside the safe fixture')
  await page.getByRole('button', { name: 'Save reflection' }).click()
  await expect(page.getByText('AI review is ready below.')).toBeVisible({ timeout: 5_000 })
  await page.locator('nav[aria-label="Time management"]').getByRole('link', { name: 'Admin' }).click()
  await expect(page.getByText(/Agent One: On plan, no tracked time/)).toBeVisible()
  await expect(page.getByText(/follow-up \(3 contributors\)/)).toBeVisible()
  await expect(page.getByText('Private reflection kept inside the safe fixture')).toHaveCount(0)
  const state = await fixture.snapshot()
  expect(state.calls.some(call => call.operation === 'rpc' && call.target === 'time_start_timer')).toBe(true)
  expect(state.calls.some(call => call.operation === 'rpc' && call.target === 'time_save_daily_plan')).toBe(true)
  expect(fixture.externalRequests.length).toBeGreaterThan(0)
  expect(JSON.stringify(fixture.externalRequests)).not.toContain('Private reflection')
})
